---
title: "About this site"
description: |
  Ce document présente XXXX
output :
  distill::distill_article:
    toc : true
    toc_depth : 3
    toc_float : true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r, echo=FALSE}
library(weights)
library(anesrake)
library(questionr)
library(Hmisc)
library(dplyr)
library(ggplot2)
```

```{r, echo=FALSE}
library(tidyverse)
library(kableExtra)
```

```{r, echo=FALSE}
library(readxl)
D <- read_excel("C:/Users/Léopold/Desktop/CU_redresse.xlsx")
```

```{r, echo=FALSE}
# recodage des données
# Je fais Oui/Non pour la variable Q14.A.bloc
D$Q14.A.bloc <- ifelse(
  D$Q14.A.bloc.num %in% c("0", "1", "2"),
  "Non",
  ifelse(
    D$Q14.A.bloc.num %in% c("3", "4"),
    "Oui",
    as.character(D$Q14.A.bloc.num)  # assurez-vous que la variable est de type caractère
  )
)
# Recodage de la variable Q14.B.voie
D$Q14.B.voie <- ifelse(
  D$Q14.B.voie.num %in% c("0", "1", "2"),
  "Non",
  ifelse(
    D$Q14.B.voie.num %in% c("3", "4"),
    "Oui",
    as.character(D$Q14.B.voie.num)
  )
)
# Recodage de la variable Q14.C.fun
D$Q14.C.fun <- ifelse(
  D$Q14.C.funclimb.num %in% c("0", "1", "2"),
  "Non",
  ifelse(
    D$Q14.C.funclimb.num %in% c("3", "4"),
    "Oui",
    as.character(D$Q14.C.funclimb.num)
  )
)
# Recodage de la variable Q14.D.pan
D$Q14.D.pan <- ifelse(
  D$Q14.D.pan.num %in% c("0", "1", "2"),
  "Non",
  ifelse(
    D$Q14.D.pan.num %in% c("3", "4"),
    "Oui",
    as.character(D$Q14.D.pan.num)
  )
)
# Recodage de la variable Q14.E.fitness
D$Q14.E.fitness <- ifelse(
  D$Q14.E.muscu.num %in% c("0", "1", "2"),
  "Non",
  ifelse(
    D$Q14.E.muscu.num %in% c("3", "4"),
    "Oui",
    as.character(D$Q14.E.muscu.num)
  )
)
# Recodage de la variable Q14.F.sauna
D$Q14.F.sauna <- ifelse(
  D$Q14.F.sauna.num %in% c("0", "1", "2"),
  "Non",
  ifelse(
    D$Q14.F.sauna.num %in% c("3", "4"),
    "Oui",
    as.character(D$Q14.F.sauna.num)
  )
)
# Recodage de la variable Q14.G.yoga
D$Q14.G.yoga <- ifelse(
  D$Q14.G.yoga.num%in% c("0", "1", "2"),
  "Non",
  ifelse(
    D$Q14.G.yoga.num %in% c("3", "4"),
    "Oui",
    as.character(D$Q14.G.yoga.num)
  )
)
# Recodage de la variable Q14.H.jeu
D$Q14.H.jeu <- ifelse(
  D$Q14.H.jeu.num %in% c("0", "1", "2"),
  "Non",
  ifelse(
    D$Q14.H.jeu.num %in% c("3", "4"),
    "Oui",
    as.character(D$Q14.H.jeu.num)
  )
)
```

```{r, echo=FALSE}
Gerland <- subset(D, Q0.A.salle == "gerland")
```

```{r, echo=FALSE}
library(DT)
```

## XYZ
### AABB
*Question ?*

```{r}
sexe_sans_pondération <- round(prop.table(table(Gerland$Q30.sexe)) * 100, 1)
sexe_avec_pondération <- round(prop.table(wtd.table(Gerland$Q30.sexe, weight = Gerland$poids)) * 100, 1)
sexe_tableau <- data.frame(
  "Sans pondération" = sexe_sans_pondération,
  "Avec pondération" = sexe_avec_pondération
)
# Supprimez la colonne "Sexe" que vous ne souhaitez pas afficher (par exemple, la troisième colonne)
sexe_tableau <- sexe_tableau[, -3]
# Utilisez kable pour formater le tableau
sexe_tableau %>%
  knitr::kable(caption = "Tableau WWWW", col.names = c("ZZ", "YY", "XX")) %>%
  kableExtra::kable_styling(bootstrap_options = "striped", full_width = FALSE)
```